import json
from difflib import SequenceMatcher
import discord

civInfo = {'Armenians': 'The Armenians : Focus: Infantry and Naval Wonder: Etchmiadzin Cathedral Unique units : Composite Bowman : Foot archer that ignores armor. Warrior Priest : Religious infantry that can fight, carry Relics , and heal allied units. Unique technologies : Cilician Fleet : Demolition Ships + 20% blast radius; Galley-line and Dromons +1 range. Fereters : Infantry (except Spearman-line) +30 hit points, Warrior Priests +100% heal speed. Civilization bonuses : Mule Carts cost -25%. Mule Cart technologies are 40% more effective. Note :First Fortified Church receives a free Relic . Long Swordsman and above, and Spearman line Note :available one Age earlier. Galley -line and Dromons * fire an additional projectile. The additional projectile for the Galley-line deals 1 damage. Team bonus : Infantry have +2 Line of Sight ',
         'Aztecs': 'The Aztecs : Focus: Infantry and Monk Wonder: Great Pyramid of Tenochtitlan Unique unit : Jaguar Warrior : Anti-infantry infantry Unique technologies : Atlatl : Skirmishers +1 attack and range. Garland Wars : Infantry +4 attack. Civilization bonuses : Start the game with an Eagle Scout . Villagers carry +3 extra resources. All military units are created 11% faster. Monks gain 5 HP for every researched Monastery technology. Start with +50 gold . Team bonus : Relics generate +33% gold ',
          'Bengalis': 'The Bengalis : Focus: Elephant and Naval Wonder: Somapura Mahavihara Unique unit : / Ratha : Mounted archer that can switch between melee and ranged attacks. Unique technologies : Paiks : Rathas and elephant units attack 20% faster. Mahayana : Villagers and Monks take up -10% population space. Civilization bonuses : Elephant units receive 25% less bonus damage and more resistant to conversion . Note :Town Centers spawn 2 Villagers when the next Age is reached. Cavalry units +2 attack vs Skirmishers . Ships regenerate 15 HP per minute. Monks +3/+3 armor. Team bonus : Trade units yield 10% food in addition to gold ',
           'Berbers': 'The Berbers : Focus: Cavalry and Naval Wonder: Hassan Tower Unique unit : Camel Archer : Mounted archer with attack bonus against mounted archers Genitour : Mounted Skirmisher Unique technologies : Kasbah : Allied Castles work 25% faster. Note :Maghrebi Camels : Camel units regenerate 0.25 HP/s. Civilization bonuses : Villagers move 5% faster in Dark Age, 10% faster starting in Feudal Age. Stable units are 15%/20% cheaper in the Castle/Imperial Age. Ships move 10% faster. Team bonus : Genitours are available at the Archery Range starting in the Castle Age',
            'Bohemians': 'The Bohemians : Focus: Gunpowder and Monk Wonder: Powder Tower of Prague Unique unit : Hussite Wagon : Tanky siege unit that can protect rear units. Houfnice : Upgrade of the Bombard Cannon , provides additional HP, attack, and blast radius. Unique technologies : Wagenburg Tactics : Gunpowder units move 15% faster. Hussite Reforms : Monks and Monastery upgrades have their gold cost replaced by food. Civilization bonuses : Blacksmiths and Universities cost -100 wood . Chemistry and Hand Cannoneer available in Castle Age . Spearman -line deals +25% bonus damage. Note :Fervor and Sanctity affect Villagers . Mining Camp technologies are free. Team bonus : Markets work 80% faster',
             'Britons': 'The Britons : Focus: Foot archer Wonder: Chichester Cathedral Unique unit : Longbowman : Long-ranged foot archer . Unique technologies : Yeomen : Gives foot archers +1 range and towers +2 attack. Warwolf : Gives Trebuchets blast damage and 100% accuracy against units. Civilization bonuses : Town Centers cost -50% wood starting in the Castle Age . Foot archers (except Skirmishers ) have +1/+2 range in the Castle/Imperial Age. Shepherds work 25% faster. Team bonus : Archery Ranges work 10% faster',
              'Bulgarians': 'The Bulgarians : Focus: Infantry and Cavalry Wonder: Preslav Round Church Unique units : Konnik : Cavalry that keeps on fighting as a dismounted infantry when killed. Dismounted Konnik : The dismounted infantry unit which appears after the death of the cavalry Konnik. Unique building : Krepost : Miniature version of the Castle , which can create the Konnik. Unique technologies : Stirrups : Cavalry attack 33% faster. Bagains : Militia line units +5 armor . Civilization bonuses : Militia line units are upgraded for free. Note :Town Centers cost -50% stone (except starting Town Center). Blacksmith and Siege Workshop technologies cost -50% food . Team bonus : Blacksmiths work 80% faster',
               'Burgundians': 'The Burgundians : Focus: Cavalry Wonder: Brussels Town Hall Unique unit : Coustillier : Cavalry unit that can charge its attack over time Flemish Militia : Infantry unit with a bonus vs cavalry; can only be obtained first via the Flemish Revolution technology Unique technologies : Burgundian Vineyards : Farmers slowly generate gold in addition to food. Note :Flemish Revolution : Upgrades all existing Villagers to Flemish Militia , and allows the training of Flemish Militia at Barracks . Civilization bonuses : Economic upgrades (except Coinage and Banking ) cost -33%  food and are available one Age earlier than other civilizations. Stable technologies are 50% cheaper. Cavalier upgrade available in the Castle Age . Gunpowder units gain +25% attack. Note :Team bonus : Relics generate 0.5 food /s in addition to gold ',
                'Burmeses': 'The Burmeses : Focus: Monk and Elephant Wonder: Shwezigon Pagoda Unique unit : Arambai : Ranged cavalry with powerful but inaccurate attack. Unique technologies : Manipur Cavalry : Gives cavalry units +4 attack against archers . Howdah : Gives Battle Elephants +1/+1 armor. Civilization bonuses : Lumber Camp technologies are free. Battle Elephants have +1/+1 armor. Infantry units have +1/+2/+3 attack in the Feudal/Castle/Imperial Age. Monastery technologies are 50% cheaper. Team bonus : Relics are visible on the map from the game start',
                 'Byzantines': 'The Byzantines : Focus: Defensive Wonder: Hagia Sophia Unique unit : Cataphract : Heavy cavalry that excels at combat against infantry and Camel Riders . Unique technologies : Greek Fire : Gives Fire Ships +1 range; Dromons +0.2 blast radius; Bombard Towers +0.5 blast radius [25% effect without friendly fire damage] Logistica : Gives Cataphracts trample damage in 0.5 tiles radius (pure 5 damage) and +6 attack against infantry . Civilization bonuses : Buildings , Walls/Gates, and Farms have +10%/+20%/+30%/+40% hit points in the Dark/Feudal/Castle/Imperial Age. Camel Rider , Skirmisher , and Spearman lines are 25% cheaper. Fire Ships and Dromons fire 25% faster. Advancing to the Imperial Age is 33% cheaper. Town Watch and Town Patrol are free. Team bonus : Monks heal 100% faster',
                  'Celtics': 'The Celtics : Focus: Infantry and Siege Wonder: Rock of Cashel Unique unit : Woad Raider : Quick infantry unit. Unique technologies : Stronghold : Castles and towers fire 33% faster; Castles can heal allied infantry units by 30 hit points per minute in an 18 tile square. Furor Celtica : Gives Siege Workshop units +40% hit points . Civilization bonuses : Infantry units move 15% faster starting from the Feudal Age . Lumberjacks work 15% faster. Siege weapons fire 25% faster. Enemy herdable animals can be converted regardless of enemy units next to them. Team bonus : Siege Workshops work 20% faster',
                   'Chineses': 'The Chineses : Focus: Archer Wonder: Hall of Prayer for Good Harvests in the Temple of Heaven complex Unique unit : Chu Ko Nu : Foot archer that fires multiple arrows. Unique technologies : Great Wall : Increases the hit points of walls and towers by +30%. Rocketry : Increases the pierce attack of Chu Ko Nu by +2, and the attack of Scorpions by +4. Civilization bonuses : Start game with +3 Villagers , but with -200 food ,-50 wood . Town Centers support 15 population (instead of 5) and have +7 Line of Sight . Technologies are 5%/10%/15% cheaper in the Feudal/Castle/Imperial Age. Demolition Ships have +50% hit points. Team bonus : Farms start with +10% food . Note :Cumans : ',
                    'Cumans': 'The Cumans : Focus: Cavalry Wonder: Sarkel Fortress (ruined) Unique units : Kipchak : Cheap multi-shot mounted archer . Unique technologies : Steppe Husbandry : Scout Cavalry line, Steppe Lancers , and Cavalry Archers are trained 100% faster. Cuman Mercenaries : Team members can create 5 free Elite Kipchaks per each Castle . Civilization bonuses : A second Town Center can be built in the Feudal Age . Note :Archery Ranges and Stables cost -75 wood . Siege Workshop and Battering Ram available in Feudal Age; Capped Ram upgrade available in Castle Age . Mounted units move 5%/10%/15% faster in Feudal/ Castle / Imperial Age . Team bonus : Palisade Walls have + 33% hit points ',
                     'Dravidians': 'The Dravidians : Focus: Infantry and Naval Wonder: Brihadisvara Temple Unique units : Urumi Swordsman : Infantry that can charge its attack to cause extra attack with Area of Effect . Thirisadai : Tanky warship that fires multiple projectiles. Unique technologies : Medical Corps : Elephant units regenerate 30 hit points per minute. Wootz Steel : Infantry and cavalry attacks ignore armor. Civilization bonuses : Receive 200 wood when advancing to the next Age. Fishermen and Fishing Ships carry +15. Barracks technologies cost -50%. Siege units cost -33% wood . Skirmishers and Elephant Archers attack 25% faster. Team bonus : Docks provide +5 population space',
                      'Ethiopians': 'The Ethiopians : Focus: Foot archer Wonder: Biete Amanuel Unique unit : Shotel Warrior : Rapidly deployed infantry with high attack but low armor and hit points . Unique technologies : Royal Heirs : Shotels and Camel units receive -3 damage from mounted units . Torsion Engines : Increases the blast radius of Siege Workshop units. Civilization bonuses : The Archer line fires 18% faster. Receive +100 food ,+100 gold whenever a new Age is reached. The Pikeman upgrade is free. Team bonus : Outposts +3 Line of Sight and stone cost removed',
                       'Frankishs': 'The Frankishs : Focus: Cavalry Wonder: St. Vitus Cathedral Unique unit : Throwing Axeman : Ranged infantry unit. Unique technologies : Bearded Axe (Throwing Axeman +1 range). Chivalry ( Stables work 40% faster). Civilization bonuses : Farm upgrades are free. Castles are 15%/25% cheaper in the Castle/Imperial Age. Mounted units have +20% hit points (starting in the Feudal Age). Foragers work 15% faster. Team bonus : Knights have +2 Line of Sight ',
                        'Georgians': 'The Georgians : Focus: Cavalry and Defensive Wonder: Svetitskhoveli Cathedral Unique unit : Monaspa : Cavalry unit that becomes stronger when other Monaspas or Knight -line units are nearby. Unique technologies : Svan Towers : Defensive structures receive +2 attack. Towers deal pass-through damage . Aznauri Cavalry : Mounted units take 15% less population space. Civilization bonuses : Start with a Mule Cart , but -50 food . Fortified Churches provide +10% work rate to Villagers Note :in a 19 tile square Note :. Units and buildings receive -20% damage (-40% instead of -25%) when fighting from higher elevation. Mounted units regenerate 5/10/15 hit points per minute in the Feudal/Castle/Imperial Age. Team bonus : Repairing buildings costs -25% resources',
                         'Gothics': 'The Gothics : Focus: Infantry Wonder: Mausoleum of Theoderic I Unique unit : Huskarl : Archer -resistant infantry unit . Unique technologies : Anarchy : Allows the creation of Huskarls at the Barracks . Perfusion : Increases the working speed of Barracks by +100%. Civilization bonuses : Infantry are 20%/25%/30%/35% cheaper in the Dark/Feudal/Castle/Imperial Age. Infantry have +1/+2/+3 attack bonus against standard buildings in the Feudal/Castle/Imperial Age. Hunters have +5 attack against aggressive huntables ( Wild Boar , Javelina , Elephant , Rhinoceros ) and carry +15 food . Hunt lasts 20% longer. Loom is researched instantly . +10 population cap in the Imperial Age . Team bonus : Barracks work 20% faster',
                          'Gurjaras': 'The Gurjaras : Focus: Cavalry and Camel Wonder: Somnath Temple Unique units : Chakram Thrower : Light infantry with a ranged melee attack and pass-through damage . Shrivamsha Rider : Light cavalry which can dodge projectile attacks. Camel Scout : Early camel unit. Unique technologies : Kshatriyas : Military units cost -25% food . Frontier Guards : Camel Riders and Elephant Archers +4 melee armor. Civilization bonuses : Start the game with a Camel Scout. Starts with 2 Forage Bushes under the Town Center. Can garrison Docks with allied Fishing Ships . Note :Can garrison Mills with herdable animals to produce food . Note :Mounted units deal +20%/+30%/+40% bonus damage in the Feudal/Castle/Imperial Age . Team bonus : Camel and elephant units are created 25% faster',
                           'Hindustanis': 'The Hindustanis : Focus: Camel and Gunpowder Wonder: Maqbara-i Humayun Unique units : Ghulam : Archer -resistant infantry unit that thrusts its spear through multiple targets. Imperial Camel Rider : Upgrade of the Heavy Camel Rider , provides additional HP and attack. Unique technologies : Grand Trunk Road : Increases the speed of all gold income by +10%. Trading fee reduced to 10%. Shatagni : Gives Hand Cannoneers +2 range. Civilization bonuses : Villagers are 8/13/18/23 % cheaper in the Dark/Feudal/Castle/Imperial Age. Camel Riders attack 20% faster. Gunpowder units have +1/+1 armor. Can build Caravanserai in the Imperial Age. Team bonus : Camel units and light cavalry units Note :have +2 attack against standard buildings ',
                            'Hunnics': 'The Hunnics : Focus: Cavalry Wonder: Arch of Constantine (ruined) Unique unit : Tarkan : Cavalry unit that excels at razing defensive structures . Unique technologies : Marauders : Allows the creation of Tarkans at the Stable . Atheism : Adds 100 years to Wonder and Relic victory countdowns and reduces enemy Relic resource generation by 50%. Civilization bonuses : Start the game with -100 wood , but with the population cap at the maximum. On Nomadic maps, the first Town Center spawns a Hunnic Horse . Mounted archers are 10%/20% cheaper in the Castle/Imperial Age. Trebuchets have +35% accuracy against units. Note :Team bonus : Stables work 20% faster',
                             'Incas': 'The Incas : Focus: Infantry Wonder: The Temple of the Sun at Machu Picchu Unique units : Kamayuk : Infantry wielding a long spear that allows attacking at range and attack bonus against cavalry . Slinger : Foot archer with a massive attack bonus against infantry . Unique technologies : Andean Sling : Slingers +1 attack and removes the minimum range from Slingers and Skirmishers . Fabric Shields : Gives Eagle Warriors , Kamayuks, and Slingers +1/+2 armor. Civilization bonuses : Military units cost -10%/-15%/-20%/-25% food in Dark/Feudal/Castle/Imperial Ages Villagers benefit from Blacksmith infantry upgrades starting in the Castle Age . Houses support 10 population . Buildings cost -15% stone . Team bonus : Start with a free Llama ',
                              'Italians': 'The Italians : Focus: Foot achers and Navy Wonder: Genoa Cathedral, Cathedral of St. Lawrence Unique unit : Genoese Crossbowman : Archer with an attack bonus against cavalry . Condottiero : Melee infantry with an attack bonus against gunpowder units . Unique technologies : Pavise : Gives foot archers (except Skirmishers) and Condottieri +1/+1 armor. Silk Road : Halves trade unit cost. Civilization bonuses : Advancing to the next Age is 15% cheaper. Dock and University technologies are 33% cheaper. Fishing Ships are 15% cheaper. Gunpowder units are 20% cheaper. Team bonus : Condottieri are available at the Barracks ',
                               'Japaneses': 'The Japaneses : Focus: Infantry Wonder: Great Buddha Hall (daibutsuden) at the Tōdai-ji temple complex Unique unit : Samurai : Fast-attacking infantry with an attack bonus against unique units . Unique technologies : Yasama : Gives towers extra arrows. Kataparuto : Makes Trebuchets pack, unpack, and fire faster. Civilization bonuses : Fishing Ships have double hit points , +2 pierce armor , and work 5%/10%/15%/20% faster in the Dark/Feudal/Castle/Imperial Age. Mills , Lumber Camps and Mining Camps are 50% cheaper. Infantry attack 33% faster starting in the Feudal Age . Mounted archers +2 attack vs. archers (except Skirmishers). Team bonus : Galleys have a +50% longer Line of Sight ',
                                'Khmers': "The Khmers : Focus: Siege and Elephant Wonder: Central shrine of the Angkor Wat temple complex Unique unit : Ballista Elephant : Heavy cavalry siege unit . Unique technologies : Tusk Swords : Battle Elephants +3 attack. Double Crossbow : Ballista Elephants and Scorpions fire an additional bolt of half strength. Civilization bonuses : No buildings are required to advance to the next age or to unlock other buildings. Battle Elephants move 10% faster. Farmers don't carry food but rather add it directly to the stockpile without any drop-off, but work 5% slower . Villagers (and Kings ) can garrison in Houses . Team bonus : Scorpions have +1 range",
                                 'Koreans': 'The Koreans : Focus: Defensive and Naval Wonder: Hwangnyong Temple Unique units : War Wagon : Heavily armored cavalry archer . Turtle Ship : Heavily armored ship that fires cannonballs. Unique technologies : Eupseong : Towers (except Bombard Towers) have +2 range. Shinkichon : Gives the Mangonel line +1 range. Civilization bonuses : Villagers have +3 Line of Sight . Stone Miners work 20% faster. Archer Armor and Tower upgrades are free ( Bombard Tower requires Chemistry ). Archer and Infantry units cost –50%  wood . Warships cost –20%  wood . Team bonus : The Mangonel line minimum range is reduced to 1 ',
                                  'Lithuanians': "The Lithuanians : Focus: Cavalry and Monk Wonder: Trakai Island Castle Unique unit : Leitis : Cavalry whose attack ignores unit's armor . Winged Hussar : Unique upgrade of the Light Cavalry replacing the Hussar (shared with the Poles ). Unique technologies : Hill Forts : Town Centers +3 range. Tower Shields : Spearman line and Skirmishers +2 pierce armor . Civilization bonuses : Each Town Center provides +100 food . Spearman line and Skirmishers move 10% faster. Each garrisoned Relic gives +1 attack to Knights and Leitis (maximum +4 ). Team bonus : Monasteries work 20% faster",
                                   'Magyars': 'The Magyars : Focus: Cavalry Wonder: Hunyad Castle Unique unit : Magyar Huszar : Light cavalry with an attack bonus against siege weapons . Unique technologies : Corvinian Army : Magyar Huszar gold cost is replaced by additional food cost. Recurve Bow : Mounted archers +1 attack and range. Civilization bonuses : Forging , Iron Casting , and Blast Furnace are free. Scout Cavalry line is 15% cheaper. Villagers kill wild animals in one strike. Note :Team bonus : Mounted archers are trained 25% faster',
                                    'Malays': 'The Malays : Focus: Infantry and Naval Wonder: Kalasan Temple Unique unit : Karambit Warrior : Cheap infantry that only takes up half a population space. Unique building : Harbor : Docks which shoots multiple arrows like a Yasama Watch Tower . Unique technologies : Thalassocracy : Upgrades Docks to Harbors . Forced Levy : Militia line costs +20 food ,-20 gold . Civilization bonuses : Advancing in Age is +66% faster . Fish Traps are 33% cheaper and provide 3×  food . Battle Elephants are 30% cheaper in the Castle Age , 40% cheaper in the Imperial Age . Infantry armor upgrades are free. Team bonus : Docks have double Line of Sight ',
                                     'Malians': 'The Malians : Focus: Infantry Wonder: Great Mosque of Djenné Unique unit : Gbeto : Fast light infantry with a powerful ranged attack. Unique technologies : Tigui : Town Centers fire +8 arrows always. Farimba : Cavalry units +5 attack. Civilization bonuses : Buildings cost -15% wood (except Farms and starting Town Center). Barracks units have +1/+2/+3 pierce armor in the Feudal/Castle/Imperial Age. Villagers drop off +10%  gold . Note :Team bonus : Universities work +80% faster',
                                      'Mayans': "The Mayans : Focus: Foot archer Wonder: Temple of the Great Jaguar (Tikal Temple I) Unique unit : Plumed Archer : Quick foot archer with high pierce armor Unique technologies : Hul'che Javelineers : Skirmishers throw two projectiles. El Dorado : Gives Eagle Warriors +40 hit points . Civilization bonuses : Start the game with an Eagle Scout . Start the game with +1 Villager , but with -50 food . Resources last 15% longer. Note :Foot archers (except Skirmishers) are 10%/20%/30% cheaper in the Feudal/Castle/Imperial Age. Team bonus : Walls and gates (both Palisade and Stone) are 50% cheaper",
                                       'Mongols': 'The Mongols : Focus: Mounted archers Wonder: Great Tent of Genghis Khan Unique unit : Mangudai : Mounted archer with an attack bonus against siege weapons . Unique technologies : Nomads : Makes Houses keep their population space if they are destroyed. Drill : Increases the movement speed of Siege Workshop units by +50%. Civilization bonuses : Cavalry archers fire 25% faster. Light Cavalry , Hussars , and Steppe Lancers have +30% HP. Note :Hunters work 40% faster. Team bonus : The Scout Cavalry line has +2 Line of Sight ',
                                        'Persians': 'The Persians : Focus: Cavalry Wonder: Taq Kasra (Arch of Ctesiphon) Unique units : War Elephant : Slow but extremely powerful cavalry unit . Savar : Unique upgrade of the Cavalier , replacing the Paladin . Unique technologies : Kamandaran : Archer -line cost changed from 25 wood ,45 gold to 60 wood . Citadels : Castles +4 attack, +3 against rams , +3 against infantry , and receive -25% bonus damage. Civilization bonuses : Start the game with +50 food ,+50 wood . Town Centers and Docks have double hit points and work 5%/10%/15%/20% faster in the Dark/Feudal/Castle/Imperial Age. Parthian Tactics available in the Castle Age. Can build Caravanserai in the Imperial Age. Team bonus : The Knight line has +2 attack against archers ',
                                         'Polishs': "The Polishs : Focus: Cavalry Wonder: Wawel Cathedral Unique unit : Obuch : Infantry whose attack reduces the target unit's armor. Winged Hussar : Unique upgrade of the Light Cavalry replacing the Hussar (shared with the Lithuanians ). Unique building : Folwark : Free upgrade to the Mill , Note :which collects 8% food from nearby constructed Farms. Unique technologies : Szlachta Privileges : Knight line costs -60% gold . Lechitic Legacy : Scout Cavalry line deals 33% trample damage in 0.5 tiles radius. Civilization bonuses : Villagers regenerate 10/15/20 HP per minute in the Feudal/Castle/Imperial Age. Stone miners generate 33% gold in addition to stone. Team bonus : The Scout Cavalry line has +1 attack vs. archers ",
                                          'Portugueses': 'The Portugueses : Focus: Naval and Gunpowder Wonder: Belém Tower Unique units : Organ Gun : Gunpowder siege unit . Caravel : Warship that can damage multiple ships in a straight line, like the Scorpion . Unique technologies : Carrack : Gives ships +1/+1 armor. Arquebus : Increases the accuracy of gunpowder units when firing at moving targets. Unique building : Feitoria : Slowly generates resources. Civilization bonuses : All units cost –20%  gold . All ships have +10% hit points. Foragers generate wood in addition to food (0.33 wood per food ). Team bonus : All technologies (excluding Age ups) research 25% faster',
                                           'Romans': "The Romans : Focus: Infantry Wonder: Colosseum Unique units : Legionary : Sturdy infantry unit . Replacement of the Two-Handed Swordsman and Champion upgrades. Centurion : Heavy cavalry unit that increases the attack and movement speeds of nearby Militia -line units. Unique technologies : Ballistas : Scorpions fire 33% faster, the Galley -line has +2 attack. Comitatenses : Militia -line, Knight -line, and Centurions train 50% faster and receive +5 charge attack over 20 seconds. Civilization bonuses : Villagers gather, build, and repair 5% faster. Galley -line and Dromon +1/+1 armor. Infantry receives double the effect from Blacksmith armor upgrades. Scorpions cost -60% gold and benefit from Ballistics . Team bonus : The Scorpion-line's minimum range is reduced to 1",
                                            'Saracens': 'The Saracens : Focus: Camel and Naval Wonder: Great Mosque of Samarra Unique unit : Mameluke : Camel cavalry with ranged melee attack, and an attack bonus against mounted units . Unique technologies : Bimaristan : Monks automatically heal multiple nearby units. Counterweights : Trebuchets and Mangonel -line +15% attack. * Civilization bonuses : The commodity trading fee is 5%. Markets cost 75  wood . Transport Ships have double hit points and +5 carry capacity. Galleys attack 25% faster. Camel units +25% hit points. Team bonus : Foot archers have +3 Note :attack against standard buildings ',
                                             'Sicilians': 'The Sicilians : Focus: Infantry and Cavalry Wonder: Monreale Cathedral Unique unit : Serjeant : Infantry unit that can also build Donjons. Unique building : Donjon : Watch Tower line variation, which can train Serjeants and is upgraded for free. Unique technologies : First Crusade : Each Town Center (up to 5) spawns a one-time group of 5 Serjeants ; also increases resistance against conversion (effect identical to Faith ). Hauberk : Knight -line +1/+2 armor. Civilization bonuses : Start with +100 stone . Note :Castles built 50% faster, Town Centers built 100% faster. Note :Land military units (except siege weapons ) receive 33% less bonus damage. Note :Farm upgrades provide additional +125% food . Note :The Donjon replaces the Watch Tower line. Team bonus : Transport Ships have +5 Line of Sight and cost -50%',
                                              'Slavics': "The Slavics : Focus: Infantry and Siege Wonder: Kizhi Pogost Unique unit : Boyar : Heavily armored cavalry , resistant to melee attack. Unique technologies : Detinets : Replaces 40% of Castles' and Towers' stone cost with wood. Druzhina : Infantry units damage adjacent units in +0.5 tiles radius with 5 damage. Civilization bonuses : Farmers work 15% faster . Supplies and Gambesons are free. Siege Workshop units are 15% cheaper. Monks move 20% faster. Team bonus : Barracks , Archery Ranges , Stables , and Siege Workshops provide +5 population ",
                                               'Spanishs': "The Spanishs : Focus: Gunpowder and Monk Wonder: Torre del Oro Unique units : Conquistador : Mounted gunpowder unit . Missionary : Mounted Monk . Unique technologies : Inquisition : Increases conversion speed for Monks and Missionaries. Missionaries +1 range. Supremacy : Gives Villagers +6 attack, +2/+2 armor, and +40 hit points . Civilization bonuses : Builders work 30% faster (20% for Wonders ) . Blacksmith upgrades don't cost gold. Cannon Galleon projectiles can track moving targets Note :and move faster. Note :Gunpowder units fire 18% faster. Note :Receive 20 gold for each technology researched. Team bonus : Trade units generate +25% gold ",
                                                'Tatars': 'The Tatars : Focus: Mounted archer Wonder: Ulugh Beg Observatory Unique units : Keshik : Cavalry that generates gold with each attack. Flaming Camel : Camel that explodes like a Petard , with attack bonuses against mounted units and elephants. Unique technologies : Silk Armor : Scout Cavalry line, Steppe Lancers and mounted archers have +1 /+1 armor. Timurid Siegecraft : Trebuchets have +2 range, enables access to the Flaming Camel . Civilization bonuses : Herdable animals contain +50% food . Note :Units do +20% damage when attacking from higher elevations (+50% instead of +25%, since the +20% is applied after the original +25%). Parthian Tactics and Thumb Ring are free. Two Sheep spawn near newly-constructed Town Centers starting in the Castle Age . Team bonus : Mounted archers have +2 Line of Sight ',
                                                 'Teutonics': 'The Teutonics : Focus: Infantry Wonder: Maria Laach Abbey Unique unit : Teutonic Knight : Slow but strong infantry . Unique technologies : Ironclad : Gives siege weapons +4 melee armor. Crenellations : Gives Castles +3 range and makes garrisoned infantry shoot arrows. Civilization bonuses : Monks have double healing range. Towers garrison twice as many units. Murder Holes and Herbal Medicine are free. Farms are 40% cheaper. Town Centers can garrison +10 units. Barracks and Stable units receive +1/+2 melee armor in the Castle/Imperial Age. Team bonus : Units resist conversion (half as effective as Faith )',
                                                  'Turkishs': 'The Turkishs : Focus: Gunpowder Wonder: Selimiye Mosque Unique unit : Janissary : More powerful version of the Hand Cannoneer . Unique technologies : Sipahi : Mounted archers +20 hit points. Artillery : +2 range for Bombard Towers , Bombard Cannons , Cannon Galleons . Civilization bonuses : Gunpowder units have +25% hit points. Gunpowder technologies are 50% cheaper; Chemistry is free. Note :Gold Miners work 20% faster. Light Cavalry and Hussar upgrades are free. Scout Cavalry line gain +1 pierce armor. Team bonus : Gunpowder units are created 25% faster',
                                                   'Vietnameses': 'The Vietnameses : Focus: Archer Wonder: Bút Tháp Unique unit : Rattan Archer : Foot archer with high pierce armor . Imperial Skirmisher : Upgrade of the Elite Skirmisher , provides additional hit points and attack. Unique technologies : Chatras : Gives Battle Elephants +100 hit points . Paper Money : Lumberjacks generate gold when working. Civilization bonuses : Archery Range units have +20% hit points. Reveal enemy initial Town Centers location at the start of the game. Conscription is free. Economic upgrades cost no wood and are researched 100% faster. Team bonus : Imperial Skirmisher upgrade is available at the Archery Range (requires the Imperial Age and Elite Skirmisher )',
                                                    'Vikings': 'The Vikings : Focus: Infantry and Naval Wonder: Borgund Stave Church Unique units : Berserk : Infantry that can regenerate . Longboat : Quick warship that fires multiple arrows. Unique technologies : Chieftains : Gives infantry +5 attack against cavalry and +4 attack against camels ; infantry generate gold when killing villagers, trade units and monks. Bogsveigar : Archer -line and Longboats +1 Attack (available since update 81058 ). Civilization bonuses : Wheelbarrow , Hand Cart upgrades free. Warships cost -15%/-15%/-20% in the Feudal/Castle/Imperial Age. Infantry have +20% hit points starting from the Feudal Age . Team bonus : Docks are 15% cheaper. Gallery : Civilization selection screen in Age of Empires II: Definitive Edition (added in update 42848 ) . Notes : ↑ This means that: Double-Bit Axe and Bow Saw provide +28% boost instead of +20%. All mining upgrades provide +21% boost instead of +15%. '}

civs = list(civInfo.keys())

def isCommand(message):
    return message.content.startswith('-civ')

async def respond(message):
    civPartial =""
    try:
        civPartial = message.content.split(' ')[1]
    except IndexError as exc:
        await message.channel.send("Example: ```-civ Cumans```")
    a = [SequenceMatcher(None, i, civPartial).ratio() for i in civs]
    await message.channel.send(embed=discord.Embed(title=civs[a.index(max(a))], description=civInfo[civs[a.index(max(a))]]))

     
